from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[2]


def read(path):
    return (ROOT / path).read_text(encoding="utf-8")


def write(path, text):
    (ROOT / path).write_text(text, encoding="utf-8")


def replace_regex(text, pattern, replacement, *, count=1, flags=re.S):
    new, n = re.subn(pattern, replacement, text, count=count, flags=flags)
    if n != count:
        raise RuntimeError(f"Expected {count} replacement(s), got {n}: {pattern[:80]}")
    return new


# ---------------- manager.py ----------------
manager = read("manager.py")
import_anchor = "from packaging.version import InvalidVersion, Version\n"
if "from factorio_settings import (" not in manager:
    manager = manager.replace(import_anchor, import_anchor + '''from factorio_settings import (\n    SETTINGS_STAGE_FILES,\n    SettingsCodecError,\n    coerce_setting_value,\n    infer_prototype_type,\n    read_mod_settings,\n    read_settings_stage_sources,\n    scan_setting_prototypes,\n    set_document_setting,\n    setting_name_likely_belongs_to_mod,\n    settings_values,\n    write_mod_settings,\n)\n''')

manager = replace_regex(
    manager,
    r"    def _mod_has_settings\(self, path: Path, kind: str\) -> bool:\n.*?(?=    def list_installed\()",
    '''    def _mod_has_settings(self, path: Path, kind: str) -> bool:\n        # Factorio has three settings-stage files, not only settings.lua.\n        return bool(read_settings_stage_sources(path, kind))\n\n''',
)

if "def mod_settings_state(self, name: str)" not in manager:
    marker = "    def open_mod_location(self, name: str) -> dict[str, str]:\n"
    methods = r'''    @property
    def mod_settings_dat_path(self) -> Path:
        return self.mods_dir / "mod-settings.dat"

    def _factorio_running(self) -> bool:
        system = platform.system().lower()
        try:
            if system == "windows":
                result = subprocess.run(
                    ["tasklist", "/FI", "IMAGENAME eq factorio.exe", "/NH"],
                    text=True,
                    capture_output=True,
                    timeout=5,
                )
                return "factorio.exe" in (result.stdout or "").lower()
            result = subprocess.run(
                ["pgrep", "-x", "factorio"],
                text=True,
                capture_output=True,
                timeout=5,
            )
            return result.returncode == 0
        except (OSError, subprocess.SubprocessError):
            return False

    @staticmethod
    def _setting_display_name(name: str) -> str:
        clean = re.sub(r"[-_.]+", " ", str(name or "")).strip()
        return clean[:1].upper() + clean[1:] if clean else str(name or "")

    def mod_settings_state(self, name: str) -> dict[str, Any]:
        """Return editable Factorio settings for one installed mod.

        Definitions are discovered from settings.lua, settings-updates.lua and
        settings-final-fixes.lua. Current values come from mod-settings.dat.
        A DAT/name heuristic is used as a fallback for settings generated by
        helper functions or Lua loops that a static scanner cannot fully parse.
        """
        name = parse_mod_name(name)
        mod = self.get_installed_mod(name)
        mod_path = Path(mod["path"])
        sources = read_settings_stage_sources(mod_path, str(mod.get("kind") or ""))
        prototypes = scan_setting_prototypes(sources)
        dat_path = self.mod_settings_dat_path
        values = {"startup": {}, "runtime-global": {}, "runtime-per-user": {}}
        dat_version = None
        dat_error = None
        warnings: list[str] = []

        if dat_path.exists():
            try:
                document = read_mod_settings(dat_path)
                values = settings_values(document)
                dat_version = ".".join(str(part) for part in document.version)
            except SettingsCodecError as exc:
                dat_error = str(exc)
                warnings.append(f"mod-settings.dat tidak dapat dibaca: {exc}")
        else:
            warnings.append("mod-settings.dat belum ada. Jalankan Factorio sampai menu utama sekali lalu tutup game.")

        source_blob = "\n".join(sources.values()).lower()
        definitions: dict[str, dict[str, Any]] = {item["name"]: dict(item) for item in prototypes}

        # Dynamic Lua helpers/loops can hide the table from static analysis.
        # Recover settings already serialized by Factorio using literal-name
        # detection and a conservative mod-prefix heuristic.
        for section, section_values in values.items():
            for setting_name, current in section_values.items():
                if setting_name in definitions:
                    continue
                literal_seen = setting_name.lower() in source_blob if source_blob else False
                prefix_match = setting_name_likely_belongs_to_mod(setting_name, name, mod.get("title") or "")
                if not (literal_seen or prefix_match):
                    continue
                definitions[setting_name] = {
                    "name": setting_name,
                    "type": infer_prototype_type(current),
                    "setting_type": section,
                    "default_value": None,
                    "minimum_value": None,
                    "maximum_value": None,
                    "allowed_values": None,
                    "hidden": False,
                    "order": None,
                    "source": "mod-settings.dat",
                    "detected_from_dat": True,
                    "ownership": "literal" if literal_seen else "prefix",
                }

        settings = []
        section_order = {"startup": 0, "runtime-global": 1, "runtime-per-user": 2}
        for setting_name, prototype in definitions.items():
            section = prototype.get("setting_type") or "startup"
            stored = setting_name in values.get(section, {})
            current = values.get(section, {}).get(setting_name, prototype.get("default_value"))
            item = dict(prototype)
            item.update({
                "display_name": self._setting_display_name(setting_name),
                "current_value": current,
                "stored": stored,
                "editable": not bool(prototype.get("hidden", False)),
            })
            settings.append(item)

        settings.sort(key=lambda item: (
            section_order.get(item.get("setting_type"), 9),
            str(item.get("order") or ""),
            str(item.get("name") or "").lower(),
        ))

        if sources and not settings:
            warnings.append(
                "Settings-stage files ditemukan, tetapi tidak ada prototype setting yang dapat dipetakan. "
                "Mod ini mungkin membuat setting secara dinamis atau hanya memodifikasi setting mod lain."
            )
        if not sources and not settings:
            warnings.append("Mod ini tidak mendeklarasikan setting standar Factorio yang terdeteksi.")

        return {
            "mod": mod,
            "dat_path": str(dat_path),
            "dat_exists": dat_path.exists(),
            "dat_version": dat_version,
            "dat_error": dat_error,
            "has_settings_stage": bool(sources),
            "settings_files": list(sources.keys()),
            "settings": settings,
            "editable_count": sum(1 for item in settings if item.get("editable")),
            "warnings": warnings,
            "factorio_running": self._factorio_running(),
        }

    def save_mod_settings(self, name: str, changes: dict[str, Any]) -> dict[str, Any]:
        name = parse_mod_name(name)
        if not isinstance(changes, dict) or not changes:
            raise ManagerError("Tidak ada perubahan setting untuk disimpan.")
        dat_path = self.mod_settings_dat_path
        if not dat_path.exists():
            raise ManagerError("mod-settings.dat belum ada. Jalankan Factorio sampai menu utama sekali lalu tutup game.")
        if self._factorio_running():
            raise ManagerError("Factorio masih berjalan. Tutup Factorio sebelum menyimpan setting agar perubahan tidak ditimpa game.")

        state = self.mod_settings_state(name)
        available = {item["name"]: item for item in state["settings"]}
        unknown = [key for key in changes if key not in available]
        if unknown:
            raise ManagerError(f"Setting tidak dikenal untuk mod {name}: {', '.join(unknown)}")

        try:
            document = read_mod_settings(dat_path)
        except SettingsCodecError as exc:
            raise ManagerError(f"Gagal membaca mod-settings.dat: {exc}") from exc

        normalized: dict[str, Any] = {}
        startup_changed = False
        runtime_global_changed = False
        runtime_user_changed = False
        for setting_name, raw_value in changes.items():
            prototype = available[setting_name]
            if not prototype.get("editable", True):
                raise ManagerError(f"Setting {setting_name} disembunyikan/terkunci oleh mod.")
            try:
                value = coerce_setting_value(prototype, raw_value)
            except (ValueError, TypeError, json.JSONDecodeError) as exc:
                raise ManagerError(f"Nilai {setting_name} tidak valid: {exc}") from exc
            try:
                set_document_setting(
                    document,
                    prototype["setting_type"],
                    setting_name,
                    value,
                    prototype.get("type"),
                )
            except SettingsCodecError as exc:
                raise ManagerError(f"Gagal menulis {setting_name}: {exc}") from exc
            normalized[setting_name] = value
            startup_changed = startup_changed or prototype["setting_type"] == "startup"
            runtime_global_changed = runtime_global_changed or prototype["setting_type"] == "runtime-global"
            runtime_user_changed = runtime_user_changed or prototype["setting_type"] == "runtime-per-user"

        backup_dir = self.backups_dir / "mod-settings"
        backup_dir.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        backup_path = backup_dir / f"mod-settings-{stamp}.dat"
        shutil.copy2(dat_path, backup_path)
        try:
            write_mod_settings(dat_path, document, backup=False)
            # Re-read immediately. A malformed write must never be reported as success.
            read_mod_settings(dat_path)
        except (OSError, SettingsCodecError) as exc:
            try:
                shutil.copy2(backup_path, dat_path)
            except OSError:
                pass
            raise ManagerError(f"Gagal menyimpan mod-settings.dat; backup dipulihkan: {exc}") from exc

        return {
            "mod": name,
            "changed_count": len(normalized),
            "changes": normalized,
            "backup": str(backup_path),
            "dat_path": str(dat_path),
            "restart_required": startup_changed,
            "runtime_global_changed": runtime_global_changed,
            "runtime_per_user_changed": runtime_user_changed,
            "message": "Startup settings memerlukan restart Factorio." if startup_changed else "Settings saved.",
        }

'''
    if marker not in manager:
        raise RuntimeError("manager open_mod_location marker not found")
    manager = manager.replace(marker, methods + marker)

write("manager.py", manager)


# ---------------- app.py ----------------
app = read("app.py")
if 'def get_mod_settings()' not in app:
    marker = '@app.post("/api/mod/open-location")\ndef open_mod_location():'
    routes = '''@app.get("/api/mod/settings")\ndef get_mod_settings():\n    try:\n        return ok(settings=manager.mod_settings_state(request.args.get("mod", "")))\n    except ManagerError as exc:\n        return fail(exc)\n\n\n@app.post("/api/mod/settings")\ndef save_mod_settings():\n    try:\n        payload = request.get_json(silent=True) or {}\n        return ok(result=manager.save_mod_settings(payload.get("mod", ""), payload.get("changes") or {}))\n    except ManagerError as exc:\n        return fail(exc)\n\n\n'''
    if marker not in app:
        raise RuntimeError("app mod location marker not found")
    app = app.replace(marker, routes + marker)
write("app.py", app)


# ---------------- flet_app.py ----------------
flet = read("flet_app.py")
new_method = r'''    async def show_mod_settings(self, e):
        name = str(e.control.data or "")
        mod = next((item for item in self.installed if item.get("name") == name), None)
        if not mod:
            self.notify(f"Mod {name} tidak ditemukan.", True)
            return

        self.set_status(f"Reading settings for {name}...")
        try:
            setting_state = await self.run_bg(manager.mod_settings_state, name)
        except Exception as exc:
            self.notify(str(exc), True)
            self.set_status("Ready")
            return

        status = ft.Text("", size=11, color="#a69d93")
        enabled = ft.Switch(label="Enabled", value=bool(mod.get("enabled")))
        editors = {}
        dialog = None

        def value_text(value):
            if isinstance(value, dict) and {"r", "g", "b"}.issubset(value):
                return ", ".join(str(value.get(key, 1.0 if key == "a" else 0.0)) for key in ("r", "g", "b", "a"))
            if value is None:
                return ""
            return str(value)

        def setting_control(setting):
            setting_name = setting["name"]
            label = setting.get("display_name") or setting_name
            disabled = not bool(setting.get("editable", True))
            current = setting.get("current_value")
            if setting.get("type") == "bool-setting":
                control = ft.Switch(label=label, value=bool(current), disabled=disabled)
            else:
                helper = [f'{setting.get("type", "setting")} · {setting_name}']
                allowed = setting.get("allowed_values")
                if allowed:
                    helper.append("allowed: " + ", ".join(map(str, allowed)))
                minimum = setting.get("minimum_value")
                maximum = setting.get("maximum_value")
                if minimum is not None or maximum is not None:
                    helper.append(f'range: {minimum if minimum is not None else "-∞"} .. {maximum if maximum is not None else "∞"}')
                control = ft.TextField(
                    label=label,
                    value=value_text(current),
                    helper_text=" · ".join(helper),
                    disabled=disabled,
                    dense=True,
                )
            editors[setting_name] = {"control": control, "setting": setting}
            source = setting.get("source") or "?"
            extra = " · detected from mod-settings.dat" if setting.get("detected_from_dat") else ""
            default = setting.get("default_value")
            details = f'Source: {source}{extra}'
            if default is not None:
                details += f' · default: {value_text(default)}'
            return ft.Container(
                padding=10,
                bgcolor="#1d1b18",
                border=ft.Border.all(1, "#39332b"),
                border_radius=8,
                content=ft.Column(spacing=5, controls=[
                    control,
                    ft.Text(details, size=9, color="#77716b"),
                ]),
            )

        section_labels = {
            "startup": ("Startup", "Loaded before the data stage; restart Factorio after changing."),
            "runtime-global": ("Map", "Global runtime settings; an existing save can synchronize/override these values."),
            "runtime-per-user": ("Per player", "Local per-player runtime settings."),
        }
        settings_controls = []
        for section in ("startup", "runtime-global", "runtime-per-user"):
            items = [item for item in setting_state["settings"] if item.get("setting_type") == section]
            if not items:
                continue
            title, note = section_labels[section]
            settings_controls.extend([
                ft.Text(title, size=16, weight=ft.FontWeight.BOLD, color="#f2d29f"),
                ft.Text(note, size=9, color="#77716b"),
                *[setting_control(item) for item in items],
                ft.Container(height=3),
            ])

        if not settings_controls:
            settings_controls = [
                ft.Container(
                    padding=12,
                    bgcolor="#211c13",
                    border=ft.Border.all(1, "#5c4828"),
                    border_radius=8,
                    content=ft.Column(spacing=4, controls=[
                        ft.Text("No editable Factorio settings detected", weight=ft.FontWeight.BOLD, color="#e4b65f"),
                        *[ft.Text(text, size=10, color="#b9aea1") for text in setting_state.get("warnings", [])],
                    ]),
                )
            ]
        elif setting_state.get("warnings"):
            settings_controls = [
                *[ft.Text("⚠ " + text, size=9, color="#e4b65f") for text in setting_state["warnings"]],
                *settings_controls,
            ]

        async def change_enabled(ev):
            wanted = bool(ev.control.value)
            try:
                await self.run_bg(manager.set_enabled, name, wanted)
                mod["enabled"] = wanted
                status.value = f'{name} {"enabled" if wanted else "disabled"}.'
                status.color = "#8fbf75"
            except Exception as exc:
                ev.control.value = not wanted
                status.value = str(exc)
                status.color = "#ff8c86"
            self.page.update()

        async def save_values(ev):
            ev.control.disabled = True
            status.value = "Saving mod-settings.dat..."
            status.color = "#a69d93"
            self.page.update()
            changes = {}
            for setting_name, entry in editors.items():
                control = entry["control"]
                if control.disabled:
                    continue
                if entry["setting"].get("type") == "bool-setting":
                    changes[setting_name] = bool(control.value)
                else:
                    changes[setting_name] = control.value
            try:
                result = await self.run_bg(manager.save_mod_settings, name, changes)
                status.value = f'Saved {result["changed_count"]} setting(s). Backup: {result["backup"]}'
                if result.get("restart_required"):
                    status.value += " · Restart Factorio required for startup settings."
                status.color = "#8fbf75"
                self.notify("Mod settings saved." + (" Restart Factorio." if result.get("restart_required") else ""))
            except Exception as exc:
                status.value = str(exc)
                status.color = "#ff8c86"
            finally:
                ev.control.disabled = False
                self.page.update()

        async def update_mod(ev):
            ev.control.disabled = True
            status.value = f"Checking {name}..."
            self.page.update()
            try:
                result = await self.run_bg(manager.update_one, name)
                status.value = f'{name}: {result["from"]} → {result["to"]}' if result.get("updated") else f"{name} already current."
                status.color = "#8fbf75"
            except Exception as exc:
                status.value = str(exc)
                status.color = "#ff8c86"
            finally:
                ev.control.disabled = False
                self.page.update()

        async def open_location(ev):
            try:
                result = await self.run_bg(manager.open_mod_location, name)
                status.value = f'Opened: {result["path"]}'
                status.color = "#8fbf75"
            except Exception as exc:
                status.value = str(exc)
                status.color = "#ff8c86"
            self.page.update()

        async def open_portal(ev):
            try:
                await self.run_bg(manager.open_mod_portal, name)
                status.value = "Opened Factorio Mod Portal."
                status.color = "#8fbf75"
            except Exception as exc:
                status.value = str(exc)
                status.color = "#ff8c86"
            self.page.update()

        def close_dialog(ev=None):
            try:
                self.page.pop_dialog()
            except Exception:
                if dialog is not None:
                    dialog.open = False
                self.page.update()

        enabled.on_change = change_enabled
        files = ", ".join(setting_state.get("settings_files") or []) or "none detected"
        dat_line = f'mod-settings.dat: {setting_state.get("dat_version") or "not available"}'
        if setting_state.get("factorio_running"):
            dat_line += " · Factorio is running; close it before Save Changes"

        deps = []
        for dep in mod.get("dependencies") or []:
            raw = str(dep.get("raw") or dep.get("name") or "").strip()
            if raw:
                deps.append(ft.Text(f"• {raw}", size=10, color="#b9aea1"))
        if not deps:
            deps.append(ft.Text("No declared dependencies.", size=10, color="#77716b"))

        save_button = ft.Button(
            "Save Changes",
            icon=ft.Icons.SAVE,
            on_click=save_values,
            disabled=not bool(editors) or not bool(setting_state.get("dat_exists")),
        )
        dialog = ft.AlertDialog(
            modal=True,
            title=ft.Row(controls=[
                ft.Icon(ft.Icons.SETTINGS_OUTLINED, color="#e48c30"),
                ft.Text(f'Mod Settings — {mod.get("title") or name}', weight=ft.FontWeight.BOLD),
            ]),
            content=ft.Container(
                width=720,
                height=560,
                content=ft.Column(
                    scroll=ft.ScrollMode.AUTO,
                    spacing=9,
                    controls=[
                        ft.Row(controls=[enabled, ft.Container(expand=True), ft.Text(f'v{mod.get("version") or "?"}', color="#f2b25c")]),
                        ft.Text(f'ID: {name} · Factorio {mod.get("factorio_version") or "?"}', size=10, color="#a69d93"),
                        ft.Text(f'Settings stage: {files}', size=9, color="#77716b"),
                        ft.Text(dat_line, size=9, color="#e4b65f" if setting_state.get("factorio_running") else "#77716b"),
                        ft.Divider(color="#39332b"),
                        ft.Text("Factorio Mod Settings", weight=ft.FontWeight.BOLD),
                        *settings_controls,
                        ft.Divider(color="#39332b"),
                        ft.Text("Dependencies", weight=ft.FontWeight.BOLD),
                        *deps,
                        ft.Divider(color="#39332b"),
                        status,
                    ],
                ),
            ),
            actions=[
                ft.Button("Open folder", icon=ft.Icons.FOLDER_OPEN, on_click=open_location, bgcolor="#24211e", color="#d8d0c7"),
                ft.Button("Mod Portal", icon=ft.Icons.OPEN_IN_NEW, on_click=open_portal, bgcolor="#24211e", color="#d8d0c7"),
                ft.Button("Check / Update", icon=ft.Icons.SYSTEM_UPDATE_ALT, on_click=update_mod, bgcolor="#24211e", color="#d8d0c7"),
                save_button,
                ft.TextButton("Close", on_click=close_dialog),
            ],
        )
        self.page.show_dialog(dialog)
        self.set_status("Ready")
        self.page.update()

'''
flet = replace_regex(
    flet,
    r"    async def show_mod_settings\(self, e\):\n.*?(?=    async def toggle_mod\(self, e\):)",
    new_method,
)
write("flet_app.py", flet)


# ---------------- static/app.js ----------------
js = read("static/app.js")
new_web = r'''function formatModSettingValue(value) {
    if (value && typeof value === "object" && !Array.isArray(value) && ["r","g","b"].every(k => k in value)) {
        return ["r","g","b","a"].map(k => value[k] ?? (k === "a" ? 1 : 0)).join(", ");
    }
    return value == null ? "" : String(value);
}

function modSettingInputHTML(setting) {
    const name = escapeHTML(setting.name);
    const label = escapeHTML(setting.display_name || setting.name);
    const disabled = setting.editable ? "" : "disabled";
    const current = setting.current_value;
    const allowed = setting.allowed_values || [];
    let input;
    if (setting.type === "bool-setting") {
        input = `<label class="mod-setting-bool"><input type="checkbox" data-setting-value="${name}" data-setting-type="bool-setting" ${current ? "checked" : ""} ${disabled}><span>${label}</span></label>`;
    } else if (allowed.length) {
        input = `<label>${label}<select data-setting-value="${name}" data-setting-type="${escapeHTML(setting.type)}" ${disabled}>${allowed.map(value => `<option value="${escapeHTML(value)}" ${String(value) === String(current) ? "selected" : ""}>${escapeHTML(value)}</option>`).join("")}</select></label>`;
    } else {
        const numeric = ["int-setting","double-setting"].includes(setting.type);
        const min = setting.minimum_value != null ? ` min="${escapeHTML(setting.minimum_value)}"` : "";
        const max = setting.maximum_value != null ? ` max="${escapeHTML(setting.maximum_value)}"` : "";
        input = `<label>${label}<input type="${numeric ? "number" : "text"}" ${setting.type === "double-setting" ? 'step="any"' : ""}${min}${max} value="${escapeHTML(formatModSettingValue(current))}" data-setting-value="${name}" data-setting-type="${escapeHTML(setting.type)}" ${disabled}></label>`;
    }
    const details = `${escapeHTML(setting.type || "setting")} · ${name} · source: ${escapeHTML(setting.source || "?")}${setting.detected_from_dat ? " · DAT fallback" : ""}`;
    return `<div class="real-setting-row">${input}<div class="real-setting-meta">${details}</div></div>`;
}

async function openModSettings(name) {
    const mod = state.installed.find(item => item.name === name);
    if (!mod) { toast(`Mod ${name} not found.`, "error"); return; }
    $("modalBody").innerHTML = `<div class="empty">Reading mod-settings.dat...</div>`;
    $("modal").classList.remove("hidden");

    let settingState;
    try {
        const data = await api(`/api/mod/settings?mod=${encodeURIComponent(name)}`);
        settingState = data.settings;
    } catch (err) {
        $("modalBody").innerHTML = `<div class="error-box">${escapeHTML(err.message)}</div>`;
        return;
    }

    const sectionLabels = {"startup":"Startup", "runtime-global":"Map", "runtime-per-user":"Per player"};
    const sectionNotes = {
        "startup":"Requires a Factorio restart after changes.",
        "runtime-global":"Existing saves can synchronize/override map runtime values.",
        "runtime-per-user":"Local per-player runtime values.",
    };
    const sections = ["startup","runtime-global","runtime-per-user"].map(section => {
        const items = (settingState.settings || []).filter(item => item.setting_type === section);
        if (!items.length) return "";
        return `<section class="real-setting-section"><h3>${sectionLabels[section]}</h3><p class="hint">${sectionNotes[section]}</p>${items.map(modSettingInputHTML).join("")}</section>`;
    }).join("");
    const warnings = (settingState.warnings || []).map(text => `<div class="mod-setting-warning">⚠ ${escapeHTML(text)}</div>`).join("");
    const deps = (mod.dependencies || []).map(dep => `<div class="mod-setting-dep">• ${escapeHTML(dep.raw || dep.name || "")}</div>`).join("") || `<div class="hint">No declared dependencies.</div>`;
    const files = (settingState.settings_files || []).join(", ") || "none detected";
    const hasEditors = (settingState.settings || []).some(item => item.editable);

    $("modalBody").innerHTML = `
        <div class="mod-settings-head"><div class="mod-icon">${escapeHTML((mod.title || mod.name).slice(0,2).toUpperCase())}</div><div><h2>${escapeHTML(mod.title || mod.name)}</h2><p>${escapeHTML(mod.name)} · v${escapeHTML(mod.version)} · Factorio ${escapeHTML(mod.factorio_version || "?")}</p></div></div>
        <div class="mod-settings-grid">
            <div><span>Author</span><strong>${escapeHTML(mod.author || "?")}</strong></div>
            <div><span>Settings stage</span><strong>${escapeHTML(files)}</strong></div>
            <div><span>mod-settings.dat</span><strong>${escapeHTML(settingState.dat_version || "not available")}</strong></div>
            <div><span>Editable</span><strong>${settingState.editable_count || 0}</strong></div>
        </div>
        <label class="checkbox-row"><input type="checkbox" id="modalModEnabled" ${mod.enabled ? "checked" : ""}><span>Enabled</span></label>
        ${settingState.factorio_running ? `<div class="mod-setting-warning">Factorio is running. Close it before saving settings.</div>` : ""}
        ${warnings}
        <div class="real-settings-editor">${sections || `<div class="empty">No editable Factorio settings detected for this mod.</div>`}</div>
        <div class="dependency-preview"><strong>Dependencies</strong>${deps}</div>
        <div class="actions mod-settings-actions">
            <button class="ghost" id="modalOpenFolder">Open Folder</button>
            <button class="ghost" id="modalOpenPortal">Mod Portal</button>
            <button class="ghost" id="modalUpdateMod">Check / Update</button>
            <button id="modalSaveSettings" ${!hasEditors || !settingState.dat_exists ? "disabled" : ""}>Save Changes</button>
        </div>
        <p class="hint" id="modalModStatus"></p>`;

    $("modalModEnabled").addEventListener("change", async e => {
        try { await api("/api/enable", {method:"POST", body:JSON.stringify({mod:name, enabled:e.target.checked})}); mod.enabled=e.target.checked; $("modalModStatus").textContent=`${name} ${e.target.checked ? "enabled" : "disabled"}.`; await loadInstalled(); }
        catch(err){ e.target.checked=!e.target.checked; $("modalModStatus").textContent=err.message; }
    });
    $("modalOpenFolder").addEventListener("click", async () => {
        try { const data=await api("/api/mod/open-location", {method:"POST", body:JSON.stringify({mod:name})}); $("modalModStatus").textContent=`Opened ${data.result.path}`; }
        catch(err){ $("modalModStatus").textContent=err.message; }
    });
    $("modalOpenPortal").addEventListener("click", () => window.open(`https://mods.factorio.com/mod/${encodeURIComponent(name)}`, "_blank", "noopener"));
    $("modalUpdateMod").addEventListener("click", async e => {
        busy(e.currentTarget,true,"Updating...");
        try { const data=await api("/api/update", {method:"POST", body:JSON.stringify({mod:name})}); $("modalModStatus").textContent=data.result.updated ? `${name}: ${data.result.from} → ${data.result.to}` : `${name} already current.`; await loadInstalled(); }
        catch(err){ $("modalModStatus").textContent=err.message; }
        finally{ busy(e.currentTarget,false); }
    });
    $("modalSaveSettings").addEventListener("click", async e => {
        const changes = {};
        document.querySelectorAll("[data-setting-value]").forEach(control => {
            changes[control.dataset.settingValue] = control.dataset.settingType === "bool-setting" ? control.checked : control.value;
        });
        busy(e.currentTarget, true, "Saving...");
        try {
            const data = await api("/api/mod/settings", {method:"POST", body:JSON.stringify({mod:name, changes})});
            $("modalModStatus").textContent = `Saved ${data.result.changed_count} setting(s).${data.result.restart_required ? " Restart Factorio for startup settings." : ""}`;
            toast("Mod settings saved." + (data.result.restart_required ? " Restart Factorio." : ""));
        } catch(err) { $("modalModStatus").textContent=err.message; }
        finally { busy(e.currentTarget,false); }
    });
}

'''
js = replace_regex(
    js,
    r"function openModSettings\(name\) \{\n.*?(?=// ---------- Factorio-style Mod Portal browser ----------)",
    new_web,
)
if '$("modalClose").addEventListener' not in js:
    anchor = 'document.querySelectorAll(".nav-item").forEach(button => button.addEventListener("click", () => switchView(button.dataset.view)));\n'
    js = js.replace(anchor, anchor + '$("modalClose").addEventListener("click", closeModal);\n$("modal").addEventListener("click", e => { if (e.target === $("modal")) closeModal(); });\n')
write("static/app.js", js)


# ---------------- static/style.css ----------------
css = read("static/style.css")
if ".real-settings-editor" not in css:
    css += r'''

/* Real per-mod Factorio settings editor */
.modal:not(.hidden) {
    position: fixed;
    inset: 0;
    z-index: 200;
    display: grid !important;
    place-items: center;
    padding: 24px;
    background: rgba(0, 0, 0, .72);
}
.modal-card {
    position: relative;
    width: min(900px, 96vw);
    max-height: 90vh;
    overflow: auto;
    padding: 22px;
    background: #24272b;
    border: 1px solid #4b4640;
    border-radius: 14px;
    box-shadow: 0 24px 70px rgba(0,0,0,.55);
}
.modal-close {
    position: absolute;
    right: 12px;
    top: 10px;
    width: 36px;
    height: 36px;
    padding: 0;
    background: transparent;
    color: #bcb5ad;
    font-size: 24px;
}
.mod-settings-head { display:flex; gap:12px; align-items:center; margin-bottom:14px; padding-right:42px; }
.mod-settings-head h2 { margin:0 0 4px; }
.mod-settings-head p { margin:0; color:var(--muted); font-size:12px; }
.mod-settings-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:8px; margin-bottom:10px; }
.mod-settings-grid > div { padding:9px; background:#1b1a18; border:1px solid var(--border); border-radius:7px; }
.mod-settings-grid span { display:block; color:var(--muted); font-size:10px; margin-bottom:4px; }
.mod-settings-grid strong { font-size:11px; overflow-wrap:anywhere; }
.real-settings-editor { display:grid; gap:12px; margin:12px 0; }
.real-setting-section { padding:12px; background:#1d1b18; border:1px solid #39332b; border-radius:9px; }
.real-setting-section h3 { color:#f2d29f; margin-bottom:2px; }
.real-setting-row { margin-top:9px; padding:10px; background:#151412; border:1px solid #36312b; border-radius:7px; }
.real-setting-row label { margin:0; color:#ece5dc; }
.real-setting-row label > input:not([type=checkbox]), .real-setting-row label > select { margin-top:6px; }
.mod-setting-bool { display:flex !important; align-items:center; gap:8px; }
.mod-setting-bool input { width:auto; }
.real-setting-meta { margin-top:5px; color:#77716b; font-size:9px; overflow-wrap:anywhere; }
.mod-setting-warning { margin:7px 0; padding:8px 10px; border-left:3px solid #d4a94c; background:#211c13; color:#e4c17b; font-size:11px; }
.mod-setting-dep { margin-top:4px; color:#c7beb4; font-size:11px; }
.mod-settings-actions { flex-wrap:wrap; margin-top:12px; }
@media (max-width:760px) { .mod-settings-grid { grid-template-columns:1fr 1fr; } .modal:not(.hidden){padding:8px;} }
'''
write("static/style.css", css)


# ---------------- pyproject / README ----------------
pyproject = read("pyproject.toml").replace('version = "2.3.0"', 'version = "2.4.0"')
write("pyproject.toml", pyproject)

readme = read("README.md")
if "Real per-mod settings editor" not in readme:
    readme += '''\n\n## Real per-mod settings editor (2.4)\n\nThe Settings button for an installed mod now scans all three Factorio settings-stage files\n(`settings.lua`, `settings-updates.lua`, and `settings-final-fixes.lua`), decodes the local\n`mod-settings.dat` PropertyTree, and exposes Startup / Map / Per-player values in both Flet\nand Flask UIs. Saves are validated, backed up, written atomically, and re-read before success\nis reported. Close Factorio before writing settings.\n'''
write("README.md", readme)

print("Applied v2.4.0 real mod settings editor patch")
